### ISSUE TITLE
[enhancement][module] Implementing some module_utils for refactoring/centralizing things

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#104]
##### SUMMARY
We've talked about this now quite often in other issues so I thought an issue might help to get it centralized or linked better.
It may be a benefit to have some centralized and reusable code to the the modules more streamlined and maybe even ease the maintainability of the code overall.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
all modules

##### ADDITIONAL INFORMATION
I've already played around with this a little bit - I will upload my code over at my forked repo so you first might have a look at it.
Basically I just thought about getting `plugins/module_utils/zapiwrapper.py` and `plugins/module_utils/zabbixbase.py` with each a class to derive of for now. Grafana is a good example and some other collections make it like this too.

This way the transition to the inherited classes would be easily manageable as the individual module classes can inherit the base classes but also do their own functions still and nothing would get compromised at all. Over time more code could get centralized. Another file like `plugins/module_utils/helper.py` could handle the various function currently in every module.

Imo, this approach might also ease the transition over from the old modules and to 5.0 wdyt?

**Comment by rockaut** [comment]
Also this way one could create his own collection copy over one or more modules or module_utils and "redirect" things through altering `import` statements and with proper FQCN usage. With this, quick-fixes for specialized environments or bugs are good manageable even in enterprise environments - heck, one could even use multiple versions at one if wanted.

Thought this might then be even worth documenting or something for wiki?

**Comment by rockaut** [comment]
Pushed to my fork under https://github.com/rockaut/community.zabbix/tree/refactor_test
Somewhat useless for now but should be a starting point.

For example, changing in zabbix_action.py:

```python

class Zapi(ZapiWrapper):
    """
    A simple wrapper over the Zabbix API
    """
    # removed __init__ here

class Action(ZabbixBase):
    """
    Restructures the user defined action data to fit the Zabbix API requirements
    """
    # removed __init__ here

    def _construct_parameters(self, **kwargs):
```

**Comment by D3DeFi** [comment]
looks good to me and can be easily extended

> Thought this might then be even worth documenting or something for wiki?

Small steps at a time I would say :)

**Comment by D3DeFi** [comment]
Do we keep this open since #107 has been merged already. Will you link followup PRs to this one as well?

**Comment by rockaut** [comment]
Please keep it open for now until we have added the basic function we like to add.
Also I think it might work as a gatekeeper issue to link the other refactors coming.

**Comment by rockaut** [comment]
- [ ] zabbix_action
- [ ] **zabbix_discovery_rule**
- [x] zabbix_group
- [x] zabbix_group_info
- [ ] zabbix_host
- [ ] zabbix_host_events_info
- [ ] zabbix_host_info
- [ ] zabbix_hostmacro
- [ ] zabbix_maintenance
- [ ] zabbix_map
- [ ] zabbix_mediatype
- [ ] _zabbix_proxy_
- [ ] _zabbix_screen_
- [ ] _zabbix_service_
- [ ] _zabbix_template_
- [ ] _zabbix_template_info_
- [ ] _zabbix_user_
- [ ] _zabbix_user_info_
- [ ] **zabbix_usergroup**
- [ ] _zabbix_valuemap_

**Comment by rockaut** [comment]
- [ ] zabbix_action
- [ ] **zabbix_discovery_rule**
- [x] ~~zabbix_group~~ see #123
- [x] ~~zabbix_group_info~~ see #123
- [ ] zabbix_host
- [ ] zabbix_host_events_info
- [ ] zabbix_host_info
- [ ] zabbix_hostmacro
- [ ] _zabbix_maintenance_ see #155 
- [ ] _zabbix_map_ see #154 
- [ ] _zabbix_mediatype_ see #153
- [x] zabbix_proxy see #143
- [ ] _zabbix_screen_ see #142
- [x] zabbix_service see #141
- [x] zabbix_template see #140
- [x] zabbix_template_info see #139
- [x] zabbix_user see #138
- [x] zabbix_user_info see #137
- [ ] **zabbix_usergroup**
- [x] zabbix_valuemap see #136

**Comment by rockaut** [comment]
- [ ] _zabbix_action_ see #160
- [ ] _zabbix_discovery_rule_ see #169 
- [x] ~~zabbix_group~~ see #123
- [x] ~~zabbix_group_info~~ see #123
- [x] ~~zabbix_host~~ see #159 
- [x] ~~zabbix_host_events_info~~ see #158 
- [x] ~~zabbix_host_info~~ see #157
- [x] ~~zabbix_hostmacro~~ see #156
- [x] ~~zabbix_maintenance~~ see #155 
- [x] ~~zabbix_map_ see~~ #154 
- [ ] _zabbix_mediatype_ see #153
- [x] ~~zabbix_proxy~~ see #143
- [ ] _zabbix_screen_ see #142
- [x] ~~zabbix_service~~ see #141
- [x] ~~zabbix_template~~ see #140
- [x] ~~zabbix_template_info~~ see #139
- [x] ~~zabbix_user~~ see #138
- [x] ~~zabbix_user_info~~ see #137
- [ ] _zabbix_usergroup_ see #168 
- [x] ~~zabbix_valuemap~~ see #136

**Comment by rockaut** [comment]
With the last PRs checks now doing well I'm finished with this.

**Comment by D3DeFi** [comment]
Once again, awesome job @rockaut! Thank you for beeing our pioneer for a future unification. I will try to get behing the zabbix_screen more this weekend so we can get that last one going as well

**Comment by D3DeFi** [comment]
Perfect, checklist done. Thank you sooo much for putting your time into this. I am already looking forward to future direction (lets leave discussions regarding that to gitter and possibly other issues once we release 1.x.x)

Closing this issue
